import requests 

# CREDIT TO https://www.geeksforgeeks.org/how-to-download-an-image-from-a-url-in-python/

class imageDownloader():

  def downloadImageUrl(fileName : str, url : str):

      '''
      Downloads a given url as a given file name to this PyQt6 project

      args: 
        filename (string): the name of the file to export the image link to
                           Common filenames for this project:
                           seedColorDemoImage.png - the seed color for the palettes
                           currentPalette.png - the focused palette generated by the seed color
        url (string): url to the image link
      '''
      # Demo link
      # url = 'http://www.colourlovers.com/img/219BAA/100/100/Gandola_turquoise.png'
      
      # This statement requests the resource at 
      # the given link, extracts its contents 
      # and saves it in a variable 
      data = requests.get(url)
      status_code = data.status_code # The error/success code
      content = data.content # The actual meat of the code
      
      if status_code == 200:
        
          # Opening a new file named img with extension .png 
          # This file would store the data of the image file 
          f = open(fileName,'wb') 

          # Storing the image data inside the data variable to the file 
          f.write(content) 
          f.close() 
      else:
         print("An api call error occurred!  Error: ", status_code)